const crypto = require('crypto');

// Verifies the signed chatbot-login token FlyThai admin's .NET side is expected to generate once
// it adopts this (see project notes) - replaces trusting a bare, guessable [User].Id (the
// SECURITY NOTE in server.js's /api/session-from-key). Token format: "<userId>.<expiryUnixSeconds>.
// <hex HMAC-SHA256 signature>", where the signature covers the exact string "<userId>.<expiry>"
// using a secret shared with FlyThai's server (CHATBOT_KEY_SECRET) - never sent to or generated by
// the browser. A short TTL means a copied/leaked token stops working on its own within minutes,
// instead of being valid forever like a bare id.
const DEFAULT_TTL_SECONDS = 5 * 60;

function getSecret() {
  const secret = process.env.CHATBOT_KEY_SECRET;
  if (!secret) throw new Error('CHATBOT_KEY_SECRET is not configured on the chatbot server.');
  return secret;
}

function sign(userId, expirySeconds) {
  const payload = `${userId}.${expirySeconds}`;
  const signature = crypto.createHmac('sha256', getSecret()).update(payload).digest('hex');
  return `${payload}.${signature}`;
}

// For local testing only, until FlyThai's .NET side generates real tokens itself - lets us exercise
// the verify path below end to end without waiting on that integration.
function signChatbotKeyToken(userId, ttlSeconds = DEFAULT_TTL_SECONDS) {
  const expiry = Math.floor(Date.now() / 1000) + ttlSeconds;
  return sign(userId, expiry);
}

// Returns { userId } for a valid, unexpired token, or null for anything else (wrong shape, bad
// signature, expired) - deliberately returns null rather than throwing for the "invalid" cases so
// callers can't accidentally 500 instead of rejecting the login attempt.
function verifyChatbotKeyToken(token) {
  if (typeof token !== 'string') return null;
  const parts = token.split('.');
  if (parts.length !== 3) return null;
  const [userIdStr, expiryStr, signature] = parts;
  const userId = Number(userIdStr);
  const expiry = Number(expiryStr);
  if (!Number.isInteger(userId) || userId <= 0) return null;
  if (!Number.isInteger(expiry) || expiry <= 0) return null;

  const expected = crypto.createHmac('sha256', getSecret()).update(`${userIdStr}.${expiryStr}`).digest('hex');
  const provided = Buffer.from(signature, 'hex');
  const expectedBuf = Buffer.from(expected, 'hex');
  // timingSafeEqual throws on length mismatch instead of returning false - a forged signature of
  // the wrong length must still be rejected, not crash the request.
  if (provided.length !== expectedBuf.length || !crypto.timingSafeEqual(provided, expectedBuf)) return null;

  if (Math.floor(Date.now() / 1000) >= expiry) return null;
  return { userId };
}

module.exports = { signChatbotKeyToken, verifyChatbotKeyToken };
